name: Docker Image CI

on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Docker tag based on branch
        id: vars
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "DOCKER_TAG=${{ secrets.APP_NAME }}" >> $GITHUB_ENV
          else
            echo "DOCKER_TAG=${{ secrets.APP_NAME }}-DEV" >> $GITHUB_ENV
          fi

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ env.DOCKER_TAG }}:latest

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to DockerHub
        run: |
          docker tag ${{ env.DOCKER_TAG }}:latest ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_TAG }}:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_TAG }}:latest

      - name: Trigger deployment on Render via Deploy Hook
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
